# Config file for CelebA dataset (200k)

output_dir: './output'
structure: 'linear'
device_id: ('0')
dataset:
  img_dir: 'C:\girl_stylegan2'
  folder: False
  resolution: 128
sched:
  epochs: [0,0,0,0,0,8]